# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payroll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
