# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20170517_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
